# Maximum cognitive complexity allowed
cognitive-complexity-threshold = 30

# Maximum number of lines in a function
too-many-lines-threshold = 100

# Maximum number of arguments in a function
too-many-arguments-threshold = 7

# Disallow certain macros
disallowed-macros = [
  { path = "std::print", reason = "use tracing instead" },
  { path = "std::println", reason = "use tracing instead" },
]
